project:
  type: website
website:
  title: R Manuals
  navbar:
    background: primary
    right:
    - href: index.qmd
      text: Home
    - text: Manuals
      menu:
      - href: r-intro/index.html
        text: An Introduction to R
      - href: r-data/index.html
        text: R Data Import/Export
      - href: r-admin/index.html
        text: R Installation and Administration
      - href: r-exts/index.html
        text: Writing R Extensions
      - href: r-lang/index.html
        text: R Language Definition
      - href: r-ints/index.html
        text: R Internals
    - href: about.qmd
      text: About
format:
  html:
    theme:
    - cosmo
    - custom.scss
    toc: true
